# Generated by Django 3.2.9 on 2021-12-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_auto_20211214_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CantidadDeEstudiantes',
            new_name='CantidadEstudiante',
        ),
        migrations.RenameModel(
            old_name='Profesores',
            new_name='Profesor',
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
    ]
