# Generated by Django 3.2.9 on 2021-12-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_auto_20211215_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='EsNoche',
        ),
    ]
