# Generated by Django 3.2.9 on 2021-12-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_remove_curso_esnoche'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CantidadEstudiante',
            new_name='CantidadEstudiantes',
        ),
        migrations.RenameField(
            model_name='cantidadestudiantes',
            old_name='cantidad',
            new_name='cantidadEstudiantes',
        ),
    ]
